spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booklending?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: Yiran
    password: Yiran,020923
  thymeleaf:
    cache: false
server:
  servlet:
    context-path: /booklending
mybatis:
  mapper-locations: classpath*:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true